dist: trusty
language: rust
rust: nightly-2018-01-23
services: docker
sudo: required
matrix:
    include:
        # Linux
        - env: TARGET=aarch64-unknown-linux-gnu
        - env: TARGET=arm-unknown-linux-gnueabi
        - env: TARGET=arm-unknown-linux-gnueabihf
        # - env: TARGET=armv4t-unknown-linux-gnueabi
        - env: TARGET=armv5te-unknown-linux-gnueabi
        - env: TARGET=armv7-unknown-linux-gnueabihf
        - env: TARGET=i586-unknown-linux-gnu
        - env: TARGET=i686-unknown-linux-gnu
        - env: TARGET=mips64el-unknown-linux-gnuabi64
        - env: TARGET=mips64-unknown-linux-gnuabi64
        - env: TARGET=mipsel-unknown-linux-gnu
        - env: TARGET=mips-unknown-linux-gnu
        - env: TARGET=powerpc64le-unknown-linux-gnu
        - env: TARGET=powerpc64-unknown-linux-gnu
        - env: TARGET=powerpc-unknown-linux-gnu
        # - env: TARGET=s390x-unknown-linux-gnu
        # - env: TARGET=sparc64-unknown-linux-gnu
        - env: TARGET=x86_64-unknown-linux-gnu
        - env: TARGET=x86_64-unknown-linux-gnux32 IGNORE_COMPILE_TEST=1

        # musl
        # - env: TARGET=aarch64-unknown-linux-musl
        - env: TARGET=arm-unknown-linux-musleabi IGNORE_COMPILE_TEST=1
        # - env: TARGET=arm-unknown-linux-musleabihf
        - env: TARGET=armv7-unknown-linux-musleabihf IGNORE_COMPILE_TEST=1
        # - env: TARGET=i586-unknown-linux-musl
        - env: TARGET=i686-unknown-linux-musl
        # - env: TARGET=mips-unknown-linux-musl
        # - env: TARGET=mipsel-unknown-linux-musl
        - env: TARGET=x86_64-unknown-linux-musl

        # uclibc
        # - env: TARGET=mips-unknown-linux-uclibc
        # - env: TARGET=mipsel-unknown-linux-uclibc

        # Android
        - env: TARGET=aarch64-linux-android
        # - env: TARGET=arm-linux-androideabi segfaults on travis
        - env: TARGET=armv7-linux-androideabi
        - env: TARGET=i686-linux-android
        # - env: TARGET=x86_64-linux-android segfaults on travis

        # Emscripten
        - env: TARGET=asmjs-unknown-emscripten IGNORE_COMPILE_TEST=1
        # - env: TARGET=wasm32-unknown-emscripten IGNORE_COMPILE_TEST=1

        # Windows
        - env: TARGET=i686-pc-windows-gnu IGNORE_COMPILE_TEST=1
        - env: TARGET=x86_64-pc-windows-gnu IGNORE_COMPILE_TEST=1

        # BSD
        # - env: TARGET=aarch64-unknown-freebsd
        # - env: TARGET=i686-unknown-freebsd
        # - env: TARGET=i686-unknown-netbsd
        # - env: TARGET=i686-unknown-openbsd
        # - env: TARGET=sparc64-unknown-netbsd
        # - env: TARGET=x86_64-rumprun-netbsd
        # - env: TARGET=x86_64-unknown-freebsd
        # - env: TARGET=x86_64-unknown-netbsd
        # - env: TARGET=x86_64-unknown-openbsd

before_install:
    - set -e
    - rustup self update
    - rustup component add rust-src
    - echo '{"ipv6":true,"fixed-cidr-v6":"2001:db8:1::/64"}' | sudo tee /etc/docker/daemon.json
    - sudo service docker restart

install:
    - bash ci/install.sh
    - source ~/.cargo/env || true

script:
    - ci/script $TARGET
