dist: trusty
language: rust
rust: nightly-2018-05-06
services: docker
sudo: required
matrix:
    # fast_finish: true
    allow_failures:
        - env: TARGET=arm-linux-androideabi
        - env: TARGET=s390x-unknown-linux-gnu
        - env: TARGET=sparc64-unknown-linux-gnu
        - env: TARGET=wasm32-unknown-emscripten COMPILE_TEST_IGNORE=1
        - env: TARGET=x86_64-linux-android

    include:
        # Linux
        - env: TARGET=aarch64-unknown-linux-gnu
        - env: TARGET=arm-unknown-linux-gnueabi
        - env: TARGET=arm-unknown-linux-gnueabihf
        # - env: TARGET=armv4t-unknown-linux-gnueabi
        - env: TARGET=armv5te-unknown-linux-gnueabi
        - env: TARGET=armv7-unknown-linux-gnueabihf
        - env: TARGET=i586-unknown-linux-gnu
        - env: TARGET=i686-unknown-linux-gnu
        - env: TARGET=mips64el-unknown-linux-gnuabi64
        - env: TARGET=mips64-unknown-linux-gnuabi64
        - env: TARGET=mipsel-unknown-linux-gnu
        - env: TARGET=mips-unknown-linux-gnu
        - env: TARGET=powerpc64le-unknown-linux-gnu
        - env: TARGET=powerpc64-unknown-linux-gnu
        - env: TARGET=powerpc-unknown-linux-gnu
        - env: TARGET=s390x-unknown-linux-gnu # allow failures
        - env: TARGET=sparc64-unknown-linux-gnu # allow failures
        - env: TARGET=x86_64-unknown-linux-gnu
        - env: TARGET=x86_64-unknown-linux-gnux32 COMPILE_TEST_IGNORE=1

        # musl
        # - env: TARGET=aarch64-unknown-linux-musl
        - env: TARGET=arm-unknown-linux-musleabi COMPILE_TEST_STEP=1
        - env: TARGET=arm-unknown-linux-musleabi COMPILE_TEST_STEP=2
        - env: TARGET=arm-unknown-linux-musleabihf COMPILE_TEST_STEP=1
        - env: TARGET=arm-unknown-linux-musleabihf COMPILE_TEST_STEP=2
        - env: TARGET=armv7-unknown-linux-musleabihf COMPILE_TEST_STEP=1
        - env: TARGET=armv7-unknown-linux-musleabihf COMPILE_TEST_STEP=2
        - env: TARGET=i586-unknown-linux-musl COMPILE_TEST_STEP=1
        - env: TARGET=i586-unknown-linux-musl COMPILE_TEST_STEP=2
        - env: TARGET=i686-unknown-linux-musl COMPILE_TEST_STEP=1
        - env: TARGET=i686-unknown-linux-musl COMPILE_TEST_STEP=2
        - env: TARGET=mips-unknown-linux-musl COMPILE_TEST_STEP=1
        - env: TARGET=mips-unknown-linux-musl COMPILE_TEST_STEP=2
        - env: TARGET=mipsel-unknown-linux-musl COMPILE_TEST_STEP=1
        - env: TARGET=mipsel-unknown-linux-musl COMPILE_TEST_STEP=2
        - env: TARGET=x86_64-unknown-linux-musl COMPILE_TEST_STEP=1
        - env: TARGET=x86_64-unknown-linux-musl COMPILE_TEST_STEP=2

        # uclibc
        # - env: TARGET=mips-unknown-linux-uclibc
        # - env: TARGET=mipsel-unknown-linux-uclibc

        # Android
        - env: TARGET=aarch64-linux-android
        - env: TARGET=arm-linux-androideabi # allow failures
        - env: TARGET=armv7-linux-androideabi
        - env: TARGET=i686-linux-android
        - env: TARGET=x86_64-linux-android # allow failures

        # Emscripten
        - env: TARGET=asmjs-unknown-emscripten COMPILE_TEST_IGNORE=1
        - env: TARGET=wasm32-unknown-emscripten COMPILE_TEST_IGNORE=1 # allow failures

        # Windows
        - env: TARGET=i686-pc-windows-gnu COMPILE_TEST_STEP=1
        - env: TARGET=i686-pc-windows-gnu COMPILE_TEST_STEP=2
        - env: TARGET=x86_64-pc-windows-gnu COMPILE_TEST_STEP=1
        - env: TARGET=x86_64-pc-windows-gnu COMPILE_TEST_STEP=2

        # BSD
        # - env: TARGET=aarch64-unknown-freebsd
        # - env: TARGET=i686-unknown-freebsd
        # - env: TARGET=i686-unknown-netbsd
        # - env: TARGET=i686-unknown-openbsd
        # - env: TARGET=sparc64-unknown-netbsd
        # - env: TARGET=x86_64-rumprun-netbsd
        # - env: TARGET=x86_64-unknown-freebsd
        # - env: TARGET=x86_64-unknown-netbsd
        # - env: TARGET=x86_64-unknown-openbsd

before_install:
    - set -e
    - rustup self update
    - rustup component add rust-src
    - echo '{"ipv6":true,"fixed-cidr-v6":"2001:db8:1::/64"}' | sudo tee /etc/docker/daemon.json
    - sudo service docker restart

install:
    - bash ci/install.sh
    - source ~/.cargo/env || true

script:
    - ci/script $TARGET
