[package]
name = "compile-test"
version = "0.1.0"
authors = ["malbarbo"]

[dependencies]
compiletest_rs = { git = "https://github.com/malbarbo/compiletest-rs", branch = "cross-std-test" }

[build-dependencies]
cc = "1.0"
