#!/usr/bin/python3

import glob
import os
import sys

def main():
    target = sys.argv[1]

    # skip in all targets
    skip_compile_test(
        [],
        ['rfc-1937-termination-trait/termination-trait-for-result-box-error_err.rs',]
    )

    if not is_native(target):
        skip(qemu)
        skip_compile_test(qemu_run_pass, qemu_run_fail)

    if 'android' in target:
        skip(android)
        skip_compile_test(android_run_pass)

    if 'musl' in target:
        skip_compile_test(musl_run_pass)

    if 'windows' in target:
        skip(windows)
        skip_compile_test(windows_run_pass, windows_run_fail)

    if target in general:
        skip(general[target])

    if target in general_run_pass:
        skip_compile_test(general_run_pass[target])

    run_pass_step()


def run_pass_path():
    return os.path.dirname(sys.argv[0]) + '/../compile-test/tests/run-pass/'


def run_pass_step():
    step = os.environ.get('COMPILE_TEST_STEP')
    files = [f for f in os.listdir(run_pass_path()) if 'auxiliary' not in f]
    files.sort(key=lambda x: x.replace('_', '-'))
    half = int(len(files) / 2)
    if step == '1':
        skip_compile_test(files[half:])
    elif step == '2':
        skip_compile_test(files[:half])


qemu = [
    'net::tcp::tests::multiple_connect_interleaved_greedy_schedule',
    'net::tcp::tests::multiple_connect_interleaved_lazy_schedule',
    'net::tcp::tests::timeouts',
    'net::udp::tests::timeouts',
    'process::tests::uid_to_root_fails',
    'process::tests::uid_works',
    'sys::unix::ext::net::test::timeouts',
    'collections::hash::map::test_map::test_lots_of_insertions', # takes too long
    'stress',
]

qemu_run_pass = [
    'backtrace-debuginfo.rs',
    'backtrace.rs',
    'command-before-exec.rs',
    'command-exec.rs',
    'env-args-reverse-iterator.rs',
    'env-funky-keys.rs',  # QEMU_LD_PREFIX is empty
    'fds-are-cloexec.rs',
    'issue-13304.rs',
    'issue-14456.rs',
    'issue-14940.rs',
    'issue-16272.rs',
    'issue-20091.rs',
    'issue-24313.rs',
    'issue-30490.rs',
    'multi-panic.rs',
    'no-stdio.rs',
    'out-of-stack.rs',
    'panic-runtime/lto-unwind.rs',
    'print-stdout-eprint-stderr.rs',
    'process-sigpipe.rs',
    'process-spawn-with-unicode-params.rs',
    'process-status-inherits-stdin.rs',
    'segfault-no-out-of-stack.rs',
    'signal-exit-status.rs',
    'sigpipe-should-be-ignored.rs',
    'simd-target-feature-mixup.rs', # target_feature does not work on qemu
    'stack-probes-lto.rs',
    'stack-probes.rs',
    'stdio-is-blocking.rs',
    'try-wait.rs',
]

qemu_run_fail = []

# Exec format error
android = [
    'process::tests::test_add_to_env',
    'process::tests::test_capture_env_at_spawn',
    'process::tests::test_inherit_env',
    'process::tests::test_override_env',
]

windows = [
    'fs::tests::copy_file_preserves_streams',
    'fs::tests::copy_file_returns_metadata_len',
    'fs::tests::create_dir_all_with_junctions',
    'fs::tests::fchmod_works',
    'fs::tests::read_link',
    'fs::tests::realpath_works',
    'fs::tests::realpath_works_tricky',
    'fs::tests::recursive_rmdir',
    'fs::tests::recursive_rmdir_of_symlink',
    'fs::tests::symlink_noexist',
    'fs::tests::symlinks_work',
    'fs::tests::truncate_works',
    'fs::tests::unicode_path_exists',
    'fs::tests::unicode_path_is_dir',
    'net::tcp::tests::bind_error',
    'net::tcp::tests::close_readwrite_smoke',
    'net::tcp::tests::fast_rebind',
    'net::tcp::tests::shutdown_smoke',
    'net::udp::tests::bind_error',
    'process::tests::test_add_to_env', # hangs
    'process::tests::test_creation_flags',
    'process::tests::test_override_env', # hangs
    'sys::windows::os::tests::ntstatus_error',
]

general = {
    'arm-unknown-linux-gnueabi': [
        'f32::tests::test_mul_add', # 38.4 is not approximately equal to 1.2
        'f64::tests::test_mul_add', # 38.4 is not approximately equal to 1.2
    ],
    'armv5te-unknown-linux-gnueabi': [
        'f32::tests::test_mul_add', # 38.4 is not approximately equal to 1.2
        'f64::tests::test_mul_add', # 38.4 is not approximately equal to 1.2
        'atomic::int_nand', # left: `78`, right: `-4914`
        'atomic::uint_nand', # left: `78`, right: `4294962382`
    ],
    'i586-unknown-linux-gnu': [
        'f32::tests::test_float_bits_conv',
        'f64::tests::test_float_bits_conv',
        'f64::tests::test_mul_add',
    ],
    'i586-unknown-linux-musl': [
        'f32::tests::test_float_bits_conv', # left: `2144687445`,  right: `2140493141`
        'f64::tests::test_float_bits_conv', # left: `9221870836978985642`, right: `9219619037165300394`
        'f32::tests::test_atanh',
        'f32::tests::test_ln',
        'f32::tests::test_log',
        'f32::tests::test_log10',
        'f32::tests::test_log2',
    ],
    'i686-unknown-linux-gnu': [
        'f32::tests::test_float_bits_conv',
        'f64::tests::test_float_bits_conv',
        'f64::tests::test_mul_add', # left: `NaN`, right: `inf`
    ],
    'i686-pc-windows-gnu': [
        'f32::tests::test_float_bits_conv',
        'f64::tests::test_float_bits_conv',
    ],
    'i686-unknown-linux-musl': [
        'f32::tests::test_float_bits_conv',
        'f64::tests::test_float_bits_conv',
    ],
    'powerpc64le-unknown-linux-gnu': [
        'iter::test_lt', # assertion failed: a.iter().gt(b.iter()) == (a[0] > b[0])
        'option::test_ord', # assertion failed: !(nan > big)
        'tuple::test_tuple_cmp', # assertion failed: !((1.0f64, 2.0f64) > (nan, 3.0))
    ],
    'x86_64-linux-android': [
        'net::ip::tests::cmp', # assertion failed: v61 < v62
        'net::ip::tests::ip_properties', # left: `true`, right: `false`
        'net::ip::tests::ipv6_properties', # left: `true`, right: `false`
    ],
    'x86_64-unknown-linux-gnux32': [
        'net::tcp::tests::timeouts', # left: `8`, right: `16`
        'net::udp::tests::timeouts', # left: `8`, right: `16`
        'sys::unix::ext::net::test::timeouts', # left: `8`, right: `16`
    ],
    'x86_64-pc-windows-gnu': [
        'process::tests::test_process_output_error',
    ],
}

# Exec format error
android_run_pass = [
    'abort-on-c-abi.rs',
    'atomic-print.rs',
    'core-run-destroy.rs',
    'issue-10626.rs',
    'issue-33770.rs',
    'panic-runtime/abort-link-to-unwinding-crates.rs',
    'panic-runtime/abort.rs',
    'panic-runtime/lto-abort.rs',
    'process-envs.rs',
    'process-exit.rs',
    'process-remove-from-env.rs',
    'running-with-no-runtime.rs',
]

# Exec format error
musl_run_pass = [
    'abort-on-c-abi.rs',
    'atomic-print.rs',
    'crt-static-off-works.rs',
    'issue-10626.rs',
    'issue-12133-3.rs',
    'issue-33770.rs',
    'panic-runtime/abort-link-to-unwinding-crates.rs',
    'panic-runtime/abort.rs',
    'panic-runtime/lto-abort.rs',
    'process-exit.rs',
    'running-with-no-runtime.rs',
]

windows_run_pass = [
    'abort-on-c-abi.rs',
    'backtrace-debuginfo.rs',
    'backtrace.rs',
    'cci_capture_clause.rs',
    'env-home-dir.rs',
    'issue-13304.rs',
    'issue-14456.rs', # hangs
    'no-stdio.rs',
    'out-of-stack.rs',
    'process-spawn-with-unicode-params.rs',
    'process-status-inherits-stdin.rs',
    'segfault-no-out-of-stack.rs',
    'stack-probes-lto.rs',
    'stack-probes.rs',
]

windows_run_fail = [
    'args-panic.rs',
    'test-panic.rs',
    'test-should-fail-bad-message.rs',
    'test-should-panic-no-message.rs',
]

general_run_pass = {
    'aarch64-unknown-linux-gnu': [
        'struct-path-self.rs', # left: `0`, right: `1`', tests/run-pass/struct-path-self.rs:49:5
        'simd-intrinsic-generic-reduction.rs', #LLVM ERROR: Cannot select: 0x7f7fec029c30: i32 = vecreduce_mul 0x7f7fec029c98
    ],
    'arm-unknown-linux-gnueabi': [
        'intrinsics-math.rs', # 0 is not approximately equal to 2.718281828459045
        'simd-intrinsic-generic-comparison.rs', # assertion failed: (e.0 != 0) == lhs.0.le(&rhs.0)
    ],
    'armv5te-unknown-linux-gnueabi': [
        'intrinsics-math.rs', # 1.3591409142295225 is not approximately equal to 2.718281828459045
        'simd-intrinsic-generic-comparison.rs', # assertion failed: (e.0 != 0) == lhs.0.le(&rhs.0)
    ],
    'arm-unknown-linux-musleabi': [
        'simd-intrinsic-generic-comparison.rs', # assertion failed: (e.0 != 0) == lhs.0.le(&rhs.0) // simd-intrinsic-generic-comparison.rs:86:9
    ],
    'mips-unknown-linux-gnu': [
        'i128.rs',
        'next-power-of-two-overflow-ndebug.rs',
        'u128.rs',
    ],
    'mips-unknown-linux-musl': [
        'i128.rs',
        'next-power-of-two-overflow-ndebug.rs',
        'u128.rs',
    ],
    'mipsel-unknown-linux-gnu': [
        'i128.rs',
        'next-power-of-two-overflow-ndebug.rs',
        'u128.rs',
    ],
    'mipsel-unknown-linux-musl': [
        'i128.rs',
        'next-power-of-two-overflow-ndebug.rs',
        'u128.rs',
    ],
    'powerpc-unknown-linux-gnu': [
        'extern-pass-empty.rs', # segfault
        'extern-pass-TwoU16s.rs', # segfault
        'extern-pass-TwoU32s.rs', # segfault
        'extern-pass-TwoU64s.rs', # segfault
        'extern-pass-TwoU8s.rs', # segfault
        'foreign-fn-with-byval.rs', # segfault
        'issue-28676.rs', # segfault
        'panic-handler-flail-wildly.rs', # sometimes it segfaults
        'struct-return.rs', # segfault
        'task-comm-3.rs', # sometimes segfaults
        'union/union-c-interop.rs', # segfault
    ],
    'powerpc64-unknown-linux-gnu': [
        'stack-probes-lto.rs',
        'stack-probes.rs',
    ],
    'powerpc64le-unknown-linux-gnu': [
        'saturating-float-casts.rs', # left: `255`, right: `0`
        'simd-intrinsic-generic-cast.rs', # f64 -> i32 (i32x4(-1234567, 12345678, -123456792, 1234567936) != i32x4(-1234567, 12345678, -123456789, 1234567890))
    ],
    'x86_64-linux-android': [
        'simd-intrinsic-generic-elements.rs', # i32x2(100, 0) != i32x2(100, 21)
    ],
    'aarch64-linux-android': [
        'struct-path-self.rs', # left: `0`, right: `1`', tests/run-pass/struct-path-self.rs:49:5
        'simd-intrinsic-generic-reduction.rs', #LLVM ERROR: Cannot select: 0x7f7fec029c30: i32 = vecreduce_mul 0x7f7fec029c98
    ],
}


def is_native(target):
    return (target.startswith("i586") or
            target.startswith("i686") or
            target.startswith("x86_64")) and \
        "android" not in target


def skip(cases):
    if cases:
        print(" --skip ", end="")
        print(" --skip ".join(cases), end="")

def skip_compile_test(pass_, fail = []):
    skip_(pass_, 'pass')
    skip_(fail, 'fail')

def skip_(cases, kind):
    dir = os.path.dirname(sys.argv[0]) + '/../compile-test/tests/run-{}/'.format(kind)
    for case in cases:
        to = dir + '../run-{}-failing/'.format(kind) + case
        to_dir = os.path.dirname(to)
        if not os.path.exists(to_dir):
            os.makedirs(to_dir)
        try:
            os.rename(dir + case, to)
        except:
            pass

if __name__ == "__main__":
    main()
