#!/bin/bash

set -e

toml=std/Cargo.toml
mkdir -p std/

crates=(
    alloc
    core
    std
    std_unicode
)

compile_lib() {
    if [ $1 = "core" -o $1 = "std_unicode" ]; then
        return 1
    else
        return 0
    fi
}

for crate in ${crates[@]}; do
    echo == $crate ==
    path="/rust/lib/rustlib/src/rust/src/lib$crate/"

    if ! compile_lib $crate; then
        path="$path/tests/"
    fi

    cat << EOF > $toml
[package]
name="$crate"
version="0.1.0"

[lib]
path="$path/lib.rs"

[dependencies]
rand = "0.3"
libc = "0.2"
EOF

    # only lib tests, because doc tests fails wit "duplicate lang item in crate ..."
    cross test --lib "$@"

    if compile_lib $crate && [ -f "$path/tests/lib.rs" ]; then
        echo -e "[[test]]\nname=\"$crate-test\"\npath=\"$path/tests/lib.rs\"" >> $toml
        cross test --test $crate-test "$@"
    fi
done
