#!/bin/bash

set -x

# FIXME: Remove when https://github.com/japaric/cross/pull/171 got release
export ANDROID_DNS_MODE=local

# FIXME: Remove when https://github.com/japaric/cross/pull/170 got released
export CARGO_TARGET_I686_LINUX_ANDROID_RUNNER="qemu-i386 -cpu n270"

main() {
    if [ ! -z $DISABLE_TESTS ]; then
        return
    fi

    TARGET="$1"

    set -e
    dir="$(dirname $0)"
    cross="$dir/cross-test"

    mkdir -p "$dir/../compile-test/tests/run-pass-failing"
    args="$($dir/args $TARGET)"

    set +e

    ret=0
    if [ -z "$IGNORE" ]; then
        if ! $cross --manifest-path std/Cargo.toml \
                    --target $TARGET \
                    --no-fail-fast \
                    -- $args; then
            ret=1
        fi
        if ! $cross --manifest-path std/Cargo.toml \
                    --target $TARGET \
                    --release \
                    --no-fail-fast \
                    -- $args; then
            ret=1
        fi
    fi

    if [ -z "$IGNORE_COMPILE_TEST" ]; then
        if ! $cross --manifest-path compile-test/Cargo.toml \
                    --target $TARGET \
                    --no-fail-fast; then
            ret=1
        fi
    fi

    exit $ret
}

main "$@"
