#!/bin/bash

set -x

main() {
    if [ ! -z $DISABLE_TESTS ]; then
        return
    fi

    TARGET="$1"

    set -e
    dir="$(dirname $0)"
    cross="$dir/cross-test"

    mkdir -p "$dir/../compile-test/tests/run-pass-failing/panic-runtime"
    args="$($dir/args $TARGET)"

    if [ -f "$dir/../docker/$TARGET/Dockerfile" ]; then
        docker build -t japaric/$TARGET -f "$dir/../docker/$TARGET/Dockerfile" "$dir/../docker"
    fi

    set +e

    ret=0
    if [ -z "$IGNORE" ]; then
        if ! $cross --manifest-path std/Cargo.toml \
                    --target $TARGET \
                    --no-fail-fast \
                    -- $args; then
            ret=1
        fi
        if ! $cross --manifest-path std/Cargo.toml \
                    --target $TARGET \
                    --release \
                    --no-fail-fast \
                    -- $args; then
            ret=1
        fi
    fi

    if [ -z "$IGNORE_COMPILE_TEST" ]; then
        if ! cross --manifest-path compile-test/Cargo.toml \
                    --target $TARGET \
                    --no-fail-fast; then
            ret=1
        fi
    fi

    exit $ret
}

main "$@"
